
name: get python version
on:
  workflow_dispatch:
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - run: echo asdf > test.txt
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: test.txt
    
